# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

mc_version=1.20.1
fabric_loader_version=0.16.7
fabric_api_version=0.92.2+1.20.1
yarn_mappings=1.20.1+build.10

# Mod Properties
mod_version=0.0.0-dev
mod_id=knowmyname
mod_name=Know My Name!
mod_author=possible_triangle
release_type=release
possible_minecraft_versions=1.20.1
maven_group=com.possible-triangle

# Dependencies
continuity_version=3.0.0-beta.5+1.20.1

# Publishing
curseforge_project_id=629673
modrinth_project_id=PswX9vWM
repository=pssbletrngle/knowmyname